// Synthetic HTTP responses for UI behavior; this does not exercise AI quality.
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { chromium } from 'playwright-core';
const home = mkdtempSync(path.join(tmpdir(), 'autojob-ui-chat-smoke-'));
process.env.AUTOJOB_HOME = home;
for (const key of ['NOTION_TOKEN', 'ANTHROPIC_API_KEY', 'OPENAI_API_KEY']) delete process.env[key];
const { ensureInitialized } = await import('../src/init'); ensureInitialized();
const { ROOT } = await import('../src/paths');
const { startServer } = await import('../src/server/server');
const { routes } = await import('../src/server/api');
const jobs = ['A', 'B'].map(id => ({ id, title: `검증회사 ${id}`, status: 'idle', activity: '답변했습니다 · 새 지시를 기다립니다', waiting: null, executionMode: 'autojob' }));
let seq = 2;
const messages = jobs.map((j, i) => ({ seq: i + 1, job: j.id, kind: 'ai', text: `${j.title}의 작성 결과를 확인했습니다. 궁금한 점을 말씀해 주세요.` }));
const sent: Record<string, unknown>[] = [];
const opened: string[] = [];
const starts: Record<string, unknown>[] = [];
routes['POST /api/apply/jobs'] = b => ({ seq, jobs, messages: messages.filter(m => m.seq > Number(b.since || 0)) });
routes['POST /api/apply/answer'] = b => { sent.push(b); messages.push({ seq: ++seq, job: String(b.id), kind: 'you', text: String(b.text) }); return { answered: true, queued: true }; };
routes['POST /api/apply/aside'] = b => {
  const job = jobs.find(j => j.id === b.id)!; job.executionMode = 'aside'; job.activity = 'Aside용 자료 준비됨';
  return { file: '/synthetic/context.md', prompt: '합성 요청을 Aside에서 이어가 주세요', url: 'https://example.test' };
};
routes['POST /api/apply/aside/open'] = b => { opened.push(String(b.id)); return { opened: true }; };
routes['POST /api/apply/autojob'] = b => { const job = jobs.find(j => j.id === b.id)!; job.executionMode = 'autojob'; job.activity = 'Auto-Job 선택됨'; return {}; };
routes['POST /api/apply/postings'] = () => ({ postings: [], statusOptions: {} });
routes['POST /api/apply/start'] = b => { starts.push(b); jobs.push({ id: 'C', title: '새 검증회사 C', status: 'idle', waiting: null, activity: 'Aside 선택됨', executionMode: String(b.mode) }); return { started: ['C'] }; };
const { server, url } = await startServer(0);
const browser = await chromium.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: true });
const page = await browser.newPage({ viewport: { width: 1400, height: 900 } });
const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
await page.addInitScript(() => localStorage.setItem('autojob-view', JSON.stringify({ type: 'settings', id: 'applies' })));
try {
  await page.goto(url); await page.locator('.room').first().waitFor();
  const a = page.locator('.room').filter({ hasText: '검증회사 A' });
  const b = page.locator('.room').filter({ hasText: '검증회사 B' });
  const input = page.locator('.chat-foot textarea');
  await a.click(); await input.fill('왜 이 직무를 골랐어?');
  await b.click(); assert.equal(await input.inputValue(), ''); await input.fill('B 회사 이어서 작성');
  await a.click(); assert.equal(await input.inputValue(), '왜 이 직무를 골랐어?');
  await input.press('Enter'); await page.waitForFunction(() => document.querySelector<HTMLTextAreaElement>('.chat-foot textarea')?.value === '');
  assert.deepEqual(sent[0], { id: 'A', text: '왜 이 직무를 골랐어?' });
  await b.click(); assert.equal(await input.inputValue(), 'B 회사 이어서 작성');
  await page.reload(); await page.locator('.room').first().waitFor(); await b.click(); assert.equal(await input.inputValue(), 'B 회사 이어서 작성');
  assert.equal(await page.locator('body').innerText().then(s => s.includes('기록만 했다가')), false);
  await page.getByRole('button', { name: 'Aside로 이어가기', exact: true }).click();
  const nativePrompt = page.getByRole('textbox', { name: 'Aside에 붙여넣을 요청' });
  await nativePrompt.waitFor(); assert.match(await nativePrompt.inputValue(), /합성 요청/);
  assert.equal(await input.isVisible(), false);
  await page.context().grantPermissions(['clipboard-read', 'clipboard-write']);
  const opening = page.waitForResponse(r => r.url().endsWith('/api/apply/aside/open'));
  await page.getByRole('button', { name: '복사하고 Aside 열기', exact: true }).click();
  await opening;
  await page.waitForFunction(() => [...document.querySelectorAll('.modal [role="status"]')].some(el => el.textContent?.includes('복사했습니다'))).catch(async e => {
    console.log({ status: await page.locator('.modal [role="status"]').allTextContents(), errors }); throw e;
  });
  assert.deepEqual(opened, ['B']);
  assert.equal(await page.evaluate(() => navigator.clipboard.readText()), '합성 요청을 Aside에서 이어가 주세요');
  await page.getByRole('button', { name: '닫기', exact: true }).click();
  assert.equal(await page.getByRole('button', { name: '중지', exact: true }).count(), 0);
  await page.getByRole('button', { name: 'Auto-Job으로 전환', exact: true }).click();
  await input.waitFor({ state: 'visible' }); assert.equal(await input.inputValue(), 'B 회사 이어서 작성');
  const dir = path.join(ROOT, 'data/verification'); mkdirSync(dir, { recursive: true });
  await page.screenshot({ path: path.join(dir, 'conversation-ui-desktop.png'), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: path.join(dir, 'conversation-ui-mobile.png'), fullPage: true });
  await page.getByRole('button', { name: '+ 새 지원서', exact: true }).click();
  const mode = page.getByRole('combobox', { name: '지원서 작업 방식' });
  await mode.waitFor(); assert.equal(await mode.inputValue(), 'autojob');
  await page.getByPlaceholder('또는 지원 페이지 주소 직접 넣기 (https://…)').fill('https://example.test/application');
  await page.getByRole('button', { name: '넣기', exact: true }).click();
  await mode.selectOption('aside');
  await page.getByRole('button', { name: 'Aside용 자료 준비', exact: true }).click();
  await nativePrompt.waitFor();
  assert.equal(starts[0].mode, 'aside');
  assert.equal(await input.isVisible(), false);
  await page.screenshot({ path: path.join(dir, 'conversation-ui-aside.png'), fullPage: true });
  assert.deepEqual(errors, []);
  const output = { testedAt: new Date().toISOString(), synthetic: true, actualAI: false, errors, checks: ['대화방별 입력 초안 분리', '정확한 회사로 전송', '새로고침 후 초안 유지', '대화 상태 렌더링', 'Aside 자료 요청/클립보드 복사/선택한 회사로 열기', 'Aside에서 Auto-Job으로 복귀 시 초안 보존', '새 지원서 기본 Auto-Job / Aside 선택과 자료 준비'] };
  writeFileSync(path.join(dir, 'conversation-ui.json'), JSON.stringify(output, null, 2), { mode: 0o600 });
  console.log(output);
} finally { await browser.close(); await new Promise<void>(r => server.close(() => r())); rmSync(home, { recursive: true, force: true }); }
